name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/backend:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # Step 4: Push Docker Image
      - name: Push Docker Image
        run: |
          docker push $DOCKER_USERNAME/backend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # Step 5: SSH and Deploy to EC2
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull $DOCKER_USERNAME/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 8080:8080 --name backend $DOCKER_USERNAME/backend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
